### ISSUE TITLE
Importing broken on Blender 4.0

### ISSUE THREAD

**Issue by andrewfullard** [andrewfullard/Blender-ALAMO-Plugin#5]
```
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_alamo_tools\import_alo.py", line 1141, in execute
    process_active_junk()
  File "C:\Users\Andrew\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_alamo_tools\import_alo.py", line 102, in process_active_junk
    meshName = processMeshChunk()
  File "C:\Users\Andrew\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_alamo_tools\import_alo.py", line 373, in processMeshChunk
    read_material_info_chunk(currentSubMesh)
  File "C:\Users\Andrew\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_alamo_tools\import_alo.py", line 430, in read_material_info_chunk
    set_up_textures(currentSubMesh.material)
  File "C:\Users\Andrew\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_alamo_tools\import_alo.py", line 621, in set_up_textures
    my_group = material_group_basic(
  File "C:\Users\Andrew\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_alamo_tools\import_alo.py", line 507, in material_group_basic
    node_group.inputs.new('NodeSocketColor', 'Team Color')
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'
```

**Comment by andrewfullard** [comment]
Change occurred here: https://docs.blender.org/api/current/change_log.html#bpy-types-nodetree replacing the `inputs` with an `interface` https://docs.blender.org/api/current/bpy.types.NodeTree.html#bpy.types.NodeTree.interface

**Comment by PlayerSchark** [comment]
bump
